api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
        multipart: ['multipart/form-data']
    swagger:
        versions: [3]
    defaults:
        pagination_items_per_page: 10 # Default value